# Generated by Django 4.1.5 on 2023-04-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_object_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
