# Generated by Django 4.1.5 on 2023-04-07 13:39

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import utilities.json


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0167_module_status'),
        ('virtualization', '0034_standardize_description_comments'),
        ('extras', '0084_staging'),
        ('netbox_object_storage', '0002_alter_bucket_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('comments', models.TextField(blank=True)),
                ('devices', models.ManyToManyField(blank=True, default=None, related_name='s3cluster_device', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('virtualmachine', models.ManyToManyField(blank=True, default=None, related_name='s3cluster_vm', to='virtualization.virtualmachine')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='pool',
            name='cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pool_cluster', to='netbox_object_storage.storagecluster'),
        ),
        migrations.DeleteModel(
            name='Cluster',
        ),
    ]
